### ISSUE TITLE
Something wrong with the colors

### ISSUE THREAD

**Issue by brunocfalcao** [blade-ui-kit/blade-zondicons#1]
Somehow I am not able to use the color classes in the Zondicons ...

The first icon already uses my Feather icons library: 

```
<x-feathericon-film class="s-8 sm:s-12 xl:s-16 text-red-500"/>
```

The second black big icon is a Zondicon:

```
<x-zondicon-chart class="text-red-500"/>
```

![image](https://user-images.githubusercontent.com/34269950/85157196-72710900-b25b-11ea-91e1-78a3aa197272.png)

**Comment by driesvints** [comment]
Heya thanks for reporting! I moved this issue to the Zondicons repo. I fixed this in https://github.com/blade-ui-kit/blade-zondicons/releases/tag/0.1.1

Make sure to clear your views after updating!
