### ISSUE TITLE
x-zondicon doesnt work in blade x-components

### ISSUE THREAD

**Issue by ivanradojevic-web-dev** [blade-ui-kit/blade-zondicons#7]
- Library Version: blade-ui-kit/blade-zondicons": "^0.2.0
- Laravel Version: laravel/framework": "^8.12
- PHP Version: php": "^7.3|^8.0

Outside component is working, but in blade component doesn`t :(

**Comment by driesvints** [comment]
Can you please post some code and steps on how to reproduce this?

**Comment by ivanradojevic-web-dev** [comment]
@driesvints I apologize, long component-name-has-caused that I left out .blade in the name.
